# Red Team Tools Suite - GitHub Pages Configuration
# Copyright (c) 2025 Joshua Hendricks Cole (DBA: Corporation of Light)

theme: jekyll-theme-cayman
title: Red Team Tools Suite
description: Open source defensive security arsenal - 11 tools, 7 ML algorithms, 4 quantum implementations
show_downloads: true
github:
  is_project_page: true
  repository_name: AioS
  repository_url: https://github.com/Workofarttattoo/AioS
